import PageHeader from '@/components/layout/PageHeader';

export const metadata = {
  title: 'Terms of Service — The Humor Index',
  description: 'Terms of service for The Humor Index website.',
  alternates: {
    canonical: 'https://thehumorindex.com/terms',
  },
};

export const dynamic = 'force-static';

export default function TermsPage() {
  return (
    <div>
      <PageHeader
        label="Legal"
        title="Terms of Service"
        subtitle="Last updated: April 14, 2026"
      />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <div className="space-y-8 text-sm text-brand-text-secondary leading-relaxed">
          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">Use of the Site</h2>
            <p>
              The Humor Index is a comedy analytics platform that provides AI-generated scores and analysis of television comedy. By using this site, you agree to these terms. The site is provided as-is for informational and entertainment purposes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">Content and Scores</h2>
            <p>
              All scores, rankings, and analyses on The Humor Index are generated by AI and represent algorithmic assessments, not objective truths. Comedy is subjective, and our scores are one data-driven perspective. We make no guarantee that our rankings reflect any individual viewer&apos;s experience.
            </p>
          </section>

          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">Intellectual Property</h2>
            <p>
              The Humor Index methodology, scoring system, and original written content are the property of The Humor Index. Show names, episode titles, and character names are the property of their respective copyright holders. Episode ratings are courtesy of IMDb. Show metadata is sourced from TMDB.
            </p>
          </section>

          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">User Conduct</h2>
            <p>
              You agree not to scrape, reproduce, or redistribute data from The Humor Index without permission. Automated access to the site (bots, scrapers) is prohibited without prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">Newsletter</h2>
            <p>
              By subscribing to our newsletter, you consent to receive weekly emails about comedy analytics. You can unsubscribe at any time using the link in each email.
            </p>
          </section>

          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">Limitation of Liability</h2>
            <p>
              The Humor Index is provided without warranties of any kind. We are not liable for any decisions made based on our scores or content. Use the site at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the site constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-medium text-brand-text-primary mb-3">Contact</h2>
            <p>
              Questions about these terms? Reach us at{' '}
              <a href="mailto:hello@thehumorindex.com" className="text-brand-gold hover:underline">
                hello@thehumorindex.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
