"use client";

/**
 * Drop-in rotation for the pull-quote on the /rankings hero.
 * Replaces the `{heroTopJoke && (<blockquote>...)}` block.
 *
 * Markup intentionally mirrors the existing blockquote so it slots into the
 * grid cell without disturbing the layout. The right-hand HI score / grade /
 * jokes panel (about the top episode) is unaffected and stays as-is.
 *
 * SSR renders index 0 (the global #1 joke — same vibe as the original "single
 * best" framing). On mount, useEffect picks a random joke from the top-25
 * pool. The "↻" button lets a user re-roll without reloading.
 *
 * Data: public/data/top-jokes.json (generated by build_top_jokes.py).
 */

import { useEffect, useState } from "react";

type TopJoke = {
  show: string;
  show_slug: string;
  season: number;
  episode_number: number;
  episode_title: string;
  characters: string[];
  text: string;
  craft: number;
  impact: number;
  combined: number;
};

interface Props {
  topJokes: TopJoke[];
}

function pickRandomIndex(len: number, exclude: number): number {
  if (len <= 1) return 0;
  let i = Math.floor(Math.random() * len);
  if (i === exclude) i = (i + 1) % len;
  return i;
}

export default function BestJokeRotator({ topJokes }: Props) {
  const [index, setIndex] = useState(0);

  useEffect(() => {
    setIndex(pickRandomIndex(topJokes.length, -1));
  }, [topJokes.length]);

  const joke = topJokes[index] ?? topJokes[0];
  if (!joke) return null;

  const character = joke.characters?.[0] || "Top joke";

  return (
    <blockquote className="border-l-2 border-brand-gold/70 pl-4 max-w-2xl">
      <p className="text-sm sm:text-base text-white/85 italic leading-relaxed line-clamp-3">
        &ldquo;{joke.text}&rdquo;
      </p>
      <footer className="mt-2 text-[11px] text-brand-text-muted uppercase tracking-widest flex items-center gap-2 flex-wrap">
        <span>
          {character} &middot; {joke.show} &middot; craft {joke.craft.toFixed(1)} &middot; impact {joke.impact.toFixed(1)}
        </span>
        <button
          type="button"
          onClick={() => setIndex(pickRandomIndex(topJokes.length, index))}
          className="text-brand-text-muted hover:text-brand-gold transition-colors px-1.5 py-0.5 rounded border border-brand-border hover:border-brand-gold text-[10px]"
          aria-label="Show a different top joke"
          title="Show me another"
        >
          <span aria-hidden>&#8635;</span>
          <span className="sr-only sm:not-sr-only sm:ml-1">New joke</span>
        </button>
      </footer>
    </blockquote>
  );
}
