import { ShowScore, SeasonScore, EpisodeScore, EpisodeDetail, CharacterProfile } from './types';
import { DNA_TYPES, type QuizData, type ShowFingerprint } from './comedyDna';
import path from 'path';
import fs from 'fs';

function readJson<T>(relativePath: string): T {
  const filePath = path.join(process.cwd(), 'public', 'data', relativePath);
  const raw = fs.readFileSync(filePath, 'utf-8');
  return JSON.parse(raw) as T;
}

export async function getAllShows(): Promise<ShowScore[]> {
  const data = readJson<ShowScore[]>('shows.json');
  return data
    .sort((a, b) => b.humor_index - a.humor_index)
    .map((s, i) => ({ ...s, rank: i + 1 }));
}

// Actual number of jokes in the search index (what's genuinely searchable).
export async function getSearchableJokeCount(): Promise<number> {
  try {
    return (await getAllShows()).reduce((sum, s) => sum + (s.total_jokes_analyzed || 0), 0);  } catch {
    return 0;
  }
}

export async function getShow(slug: string): Promise<ShowScore | null> {
  const shows = await getAllShows();
  return shows.find(s => s.slug === slug) ?? null;
}

export async function getSeasons(slug: string): Promise<SeasonScore[]> {
  // Queued/unscored shows have no data dir — return [] instead of throwing a 500.
  try {
    return readJson<SeasonScore[]>(`${slug}/seasons.json`);
  } catch {
    return [];
  }
}

export async function getEpisodes(slug: string): Promise<EpisodeScore[]> {
  try {
    return readJson<EpisodeScore[]>(`${slug}/episodes.json`);
  } catch {
    return [];
  }
}

export async function getEpisodeDetail(
  slug: string,
  season: number,
  episode: number
): Promise<EpisodeDetail | null> {
  const s = String(season).padStart(2, '0');
  const e = String(episode).padStart(2, '0');
  try {
    return readJson<EpisodeDetail>(`${slug}/s${s}e${e}.json`);
  } catch {
    return null;
  }
}

export async function getComedyDna(slug: string): Promise<Record<string, number>> {
  try {
    const all = readJson<Record<string, Record<string, number>>>('comedy-dna.json');
    return all[slug] || {};
  } catch {
    return {};
  }
}

export async function getRecommendations(slug: string): Promise<Array<{ slug: string; name: string; score: number }>> {
  try {
    const all = readJson<Record<string, Array<{ slug: string; name: string; score: number }>>>('recommendations.json');
    const raw = all[slug] || [];
    // Filter out recommendations pointing at shows that haven't been scored yet —
    // otherwise the card renders with a 0.0 Humor Index, which reads as broken.
    const shows = readJson<Array<{ slug: string; humor_index: number }>>('shows.json');
    const scored = new Set(shows.filter(s => s.humor_index > 0).map(s => s.slug));
    return raw.filter(r => scored.has(r.slug));
  } catch {
    return [];
  }
}

export async function getCharacters(slug: string): Promise<CharacterProfile[]> {
  try {
    return readJson<CharacterProfile[]>(`${slug}/characters.json`);
  } catch {
    return [];
  }
}

export async function getCharacterJokes(
  slug: string,
  characterName: string
// eslint-disable-next-line @typescript-eslint/no-explicit-any
): Promise<{ character: CharacterProfile | null; jokes: Array<{ episode: string; season: number; episode_number: number; joke: any }> }> {
  const characters = await getCharacters(slug);
  const character = characters.find(c => c.name.toLowerCase() === characterName.toLowerCase()) ?? null;
  if (!character) return { character: null, jokes: [] };

  const episodes = await getEpisodes(slug);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const allJokes: Array<{ episode: string; season: number; episode_number: number; joke: any }> = [];

  for (const ep of episodes) {
    const detail = await getEpisodeDetail(slug, ep.season, ep.episode_number);
    if (!detail) continue;
    for (const joke of detail.jokes) {
      if (joke.characters?.some((c: string) => c.toLowerCase() === characterName.toLowerCase())) {
        allJokes.push({
          episode: ep.title,
          season: ep.season,
          episode_number: ep.episode_number,
          joke,
        });
      }
    }
  }

  return { character, jokes: allJokes };
}

// ---- Comedy DNA quiz ----

// The curated battle + recommendation joke pool (generated by comedy-dna-build).
export async function getComedyDnaQuiz(): Promise<QuizData> {
  return readJson<QuizData>('comedy-dna-quiz.json');
}

// Per-show fingerprints for the quiz recommender. Reuses the existing
// comedy-dna.json (type → share) and includes only LIVE shows (humor_index > 0),
// so the quiz catalog grows automatically as shows are scored & launched.
export async function getComedyDnaFingerprints(): Promise<ShowFingerprint[]> {
  const dna = readJson<Record<string, Record<string, number>>>('comedy-dna.json');
  const shows = await getAllShows();
  const out: ShowFingerprint[] = [];
  for (const s of shows) {
    if (s.humor_index <= 0) continue;          // skip coming-soon shows
    const dist = dna[s.slug];
    if (!dist) continue;                        // needs a comedy-dna.json entry
    out.push({
      slug: s.slug,
      name: s.name,
      fp: DNA_TYPES.map(t => dist[t] || 0),
      n: s.total_jokes_analyzed || 1,
    });
  }
  return out;
}
